apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: sample-app
  labels:
    app: static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: nginx
          image: cr.yandex/crpsmc4qd27ocei4lcpk/sample-static-site:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
